#!/bin/bash
# API 配置快速指南

echo "=========================================="
echo "  AI 内容工厂 - API 配置指南"
echo "=========================================="
echo ""

ENV_FILE="/Users/k/ai-content-factory/.env"

echo "📝 配置文件位置: $ENV_FILE"
echo ""
echo "请按照以下步骤获取并配置 API 凭证："
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  微信公众号配置"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 登录: https://mp.weixin.qq.com"
echo ""
echo "步骤："
echo "  1. 开发 -> 基本配置"
echo "  2. 获取 AppID 和 AppSecret"
echo "  3. 配置 IP 白名单"
echo ""
echo "配置项："
echo "  WECHAT_APPID=wx..."
echo "  WECHAT_SECRET=..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  小红书配置"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 开放平台: https://open.xiaohongshu.com/"
echo ""
echo "步骤："
echo "  1. 注册开发者账号（需要企业认证）"
echo "  2. 创建应用"
echo "  3. 获取 App Key 和 App Secret"
echo "  4. 账号授权获取 Access Token"
echo ""
echo "配置项："
echo "  XHS_APP_KEY=..."
echo "  XHS_APP_SECRET=..."
echo "  XHS_ACCESS_TOKEN=..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  百度统计配置"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 登录: https://tongji.baidu.com/"
echo ""
echo "步骤："
echo "  1. 登录百度统计"
echo "  2. 管理 -> API 管理 -> 获取 token"
echo "  3. 在网站列表中找到 site_id"
echo ""
echo "配置项："
echo "  BAIDU_TONGJI_TOKEN=..."
echo "  BAIDU_TONGJI_SITE_ID=..."
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "4️⃣  SEO 工具配置（可选）"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 5118: https://www.5118.com/"
echo "🔗 站长工具: http://api.tool.chinaz.com/"
echo ""
echo "配置项（可选）："
echo "  SEO_5118_TOKEN=..."
echo "  SEO_CHINAZ_KEY=..."
echo ""

echo "=========================================="
echo "📝 如何配置"
echo "=========================================="
echo ""
echo "方法 1: 手动编辑 .env 文件"
echo "  nano $ENV_FILE"
echo ""
echo "方法 2: 使用命令行添加"
echo "  echo 'WECHAT_APPID=your_value' >> $ENV_FILE"
echo ""

echo "=========================================="
echo "✅ 配置完成后测试"
echo "=========================================="
echo ""
echo "测试 SEO 优化（无需配置）："
echo "  /seo-optimize 关键词 留学申请"
echo ""
echo "测试微信公众号："
echo "  /wechat-publish 状态"
echo ""
echo "测试小红书："
echo "  /xiaohongshu-publish"
echo ""
echo "测试百度统计："
echo "  /baidu-analytics 概况"
echo ""

echo "=========================================="
echo "📚 详细文档"
echo "=========================================="
echo ""
echo "完整配置指南："
echo "  /Users/k/ai-content-factory/docs/API_SKILLS_GUIDE.md"
echo ""
echo "查看文档："
echo "  cat /Users/k/ai-content-factory/docs/API_SKILLS_GUIDE.md"
echo ""

echo "=========================================="
echo "💡 提示"
echo "=========================================="
echo ""
echo "- 可以选择性配置，不需要的可以留空"
echo "- SEO 优化工具不配置也能使用基础功能"
echo "- 配置后需要重启 Streamlit 应用生效"
echo ""
